# -*- coding: utf-8 -*-
"""spam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XR9ySbwq0zguFx9lrgdSPdFUOyuCM5qQ
"""

!pip install pandas scikit-learn

import pandas as pd

# Dataset load
data = pd.read_csv("/content/Spam.csv", encoding='latin-1')

# Useful columns
data = data[['v1', 'v2']]
data.columns = ['label', 'message']

# Convert labels
data['label'] = data['label'].map({'ham':0, 'spam':1})

# Features and labels
X = data['message']
y = data['label']

# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Convert text into numbers
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

X_train_vectors = vectorizer.fit_transform(X_train)
X_test_vectors = vectorizer.transform(X_test)

# Train model
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

model.fit(X_train_vectors, y_train)

# Accuracy
accuracy = model.score(X_test_vectors, y_test)

print("Accuracy:", accuracy)

# Test custom message
msg = ["Hey, where are you?"]

msg_vector = vectorizer.transform(msg)

prediction = model.predict(msg_vector)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Not Spam")