# -*- coding: utf-8 -*-
"""Movies

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBAM8914JVz3j5Xf6Def-GIapjbyAOFC
"""

!pip install pandas scikit-learn

import pandas as pd

# Sample movie data
movies = {
    'title': [
        'Avatar',
        'Titanic',
        'Avengers',
        'Iron Man',
        'Batman',
        '3 Idiots',
        'Dangal',
        'KGF',
        'Bahubali',
        'Pushpa'
    ],

    'genre': [
        'Action SciFi',
        'Romance Drama',
        'Action Superhero',
        'Action Tech',
        'Action Dark','Comedy Drama',
        'Sports Drama',
        'Action Crime',
        'Action Historical',
        'Action Crime'
    ]
}

df = pd.DataFrame(movies)


from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

matrix = cv.fit_transform(df['genre'])

# Similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(matrix)

# Recommendation function
def recommend(movie_name):

    movie_index = df[df['title'] == movie_name].index[0]

    scores = list(enumerate(similarity[movie_index]))

    sorted_scores = sorted(scores, key=lambda x:x[1], reverse=True)

    print("Recommended Movies:\n")

    for movie in sorted_scores[1:4]:
        print(df.iloc[movie[0]].title)

# Test
recommend("KGF")